### ISSUE TITLE
circuitBreakerStrategy never opens

### ISSUE THREAD

**Issue by warren-pieterse** [App-vNext/Polly-Samples#60]
In the Demo06_WaitAndRetryNestingCircuitBreaker the only message logged is "Strategy logging: ...". the "circuit breaker strategy: break if the action fails at least 4 times in a row" never happens?

Am I missing something?

**Comment by martincostello** [comment]
FYI @peter-csala

**Comment by peter-csala** [comment]
Let me check it. @martincostello  Please assign to me

**Comment by peter-csala** [comment]
I've found the issue. :) 

The `FailureRatio` was set to `1.0`, that means all requests should fail during the sampling period. 
But I've forget to set the `SamplingDuration` that's why it used the default value which is **30 seconds**.

After setting the `SamplingDuration` to 2 seconds then the CB breaks nicely:

![Screenshot 2023-10-12 at 14 20 00](https://github.com/App-vNext/Polly-Samples/assets/57183693/5083afd9-144c-407a-ad40-6a04ba8fde12)

I've file a PR with a fix shortly.
